// This file will be auto-generated by Supabase CLI
// For now, we define a placeholder type

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      // Tables will be defined after running migrations
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      [key: string]: any
    }
    Views: {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      [key: string]: any
    }
    Functions: {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      [key: string]: any
    }
    Enums: {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      [key: string]: any
    }
  }
}
